a=input("Enter first number:")
b=input("Enter second number:")
add=int(a)+int(b)
sub=int(a)-int(b)
mul=int(a)*int(b)
div=int(a)/int(b)
print("The sum of two number:", add)
print("The difference of two number:", sub)
print("The product of two number:", mul)
print("The quotient of two number:", div)
